### ISSUE TITLE
Works well for EH17!

### ISSUE THREAD

**Issue by JanX2** [mfherbst/down-frab-videos#7]
```
events:
  EH2017:
    fahrplan: https://eh17.easterhegg.eu/Fahrplan
    media_prefix: http://cdn.media.ccc.de/events/eh2017
    name: EH2017
    starts: '2017-04-14'
```
